name: warp
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip>=23
  - faiss-gpu
  - gcc=9.4.0
  - gxx=9.4.0

  - pip:
      # PyTorch with CUDA 12.1 support (for CUDA 12.x drivers)
      - --extra-index-url https://download.pytorch.org/whl/cu121
      - torch==2.1.0+cu121
      - torchvision==0.16.0+cu121
      - torchaudio==2.1.0+cu121
      - setuptools<81
      - bitarray
      - datasets
      - gitpython
      - jupyter
      - jupyterlab
      - ninja
      - scipy
      - tqdm
      - transformers>=4.36.0,<4.44.0
      - ujson
      - flask
      - python-dotenv
      - coremltools
      - beir
      - onnxruntime-gpu
      - onnx
      - openvino
      - optimum>=1.21.3,<1.22.0
      - optimum-intel==1.18.3
      - sentencepiece
      - jsonlines
      - tabulate
      - matplotlib
      - azure-ai-ml==1.30.0
      - azure-identity
      - azure-identity-broker==1.3.0
      - azure-storage-blob==12.27.1
      - azure-storage-file-datalake==12.22.0
      - azure-keyvault-secrets==4.10.0
